const XIRR_CASH_OUTFLOW_TYPES = [
  'BUY', 'VEST', 'ESPP_CONTRIBUTION', 'DEPOSIT', 'IPO', 'TRANSFER_IN',
  'SWITCH_IN', 'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'RIGHTS', 'CHARGES', 'AMC',
];

const XIRR_CASH_INFLOW_TYPES = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT',
  'DIVIDEND', 'INTEREST', 'RECONCILE', 'TDS',
];

const INVESTED_AMOUNT_INFLOW_TYPES = [
  'BUY', 'DEPOSIT', 'IPO', 'RIGHTS', 'TRANSFER_IN', 'SWITCH_IN',
  'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'VEST', 'ESPP_CONTRIBUTION', 'ESPP_PURCHASE',
];

const REALIZED_CASHFLOW_TYPES = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT', 'DIVIDEND', 'INTEREST',
];

const REALIZED_CASHFLOW_TYPES_REINVEST_ACCRUAL = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT', 'DIVIDEND',
];

function toSqlInList(values) {
  return values.map((v) => `'${String(v).replace(/'/g, "''")}'`).join(',');
}

const INVESTED_AMOUNT_INFLOW_TYPES_SQL = toSqlInList(INVESTED_AMOUNT_INFLOW_TYPES);

module.exports = {
  XIRR_CASH_OUTFLOW_TYPES,
  XIRR_CASH_INFLOW_TYPES,
  INVESTED_AMOUNT_INFLOW_TYPES,
  REALIZED_CASHFLOW_TYPES,
  REALIZED_CASHFLOW_TYPES_REINVEST_ACCRUAL,
  INVESTED_AMOUNT_INFLOW_TYPES_SQL,
};
