const XIRR_CASH_OUTFLOW_TYPES = [
  'BUY', 'VEST', 'ESPP_CONTRIBUTION', 'DEPOSIT', 'IPO', 'TRANSFER_IN',
  'SWITCH_IN', 'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'RIGHTS', 'CHARGES', 'AMC',
];

const XIRR_CASH_INFLOW_TYPES = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT',
  'DIVIDEND', 'INTEREST', 'RECONCILE', 'TDS',
];

const INVESTED_AMOUNT_INFLOW_TYPES = [
  'BUY', 'DEPOSIT', 'IPO', 'RIGHTS', 'TRANSFER_IN', 'SWITCH_IN',
  'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'VEST', 'ESPP_CONTRIBUTION', 'ESPP_PURCHASE',
];

const ACQUIRED_UNITS_INFLOW_TYPES = [
  'BUY', 'DEPOSIT', 'BONUS', 'SPLIT', 'IPO', 'TRANSFER_IN', 'SWITCH_IN',
  'RIGHTS', 'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'VEST', 'ESPP_PURCHASE',
];

const REALIZED_CASHFLOW_TYPES = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT', 'DIVIDEND', 'INTEREST',
];

const REALIZED_CASHFLOW_TYPES_REINVEST_ACCRUAL = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'TRANSFER_OUT', 'SWITCH_OUT', 'DIVIDEND',
];

// Cost-basis lens (portfolio summary/footer): focus on external cash movement,
// excluding internal re-allocations like SWITCH/TRANSFER between holdings.
const COST_BASIS_INVESTED_TYPES = [
  'BUY', 'DEPOSIT', 'IPO', 'RIGHTS', 'EMPLOYER_CONTRIBUTION', 'VOLUNTARY_CONTRIBUTION', 'ESPP_CONTRIBUTION',
];

// Dashboard by-type returns lens: include equity compensation acquisition events
// so denominator aligns with invested-basis interpretation for rows/totals.
const DASHBOARD_RETURNS_INVESTED_TYPES = [
  ...COST_BASIS_INVESTED_TYPES,
  'VEST',
  'ESPP_PURCHASE',
];

const COST_BASIS_RECEIVED_TYPES = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'DIVIDEND', 'INTEREST',
];

const COST_BASIS_RECEIVED_TYPES_NO_INTEREST = [
  'SELL', 'REDEMPTION', 'WITHDRAWAL', 'DIVIDEND', 'TRANSFER_OUT', 'SWITCH_OUT',
];

function toSqlInList(values) {
  return values.map((v) => `'${String(v).replace(/'/g, "''")}'`).join(',');
}

const INVESTED_AMOUNT_INFLOW_TYPES_SQL = toSqlInList(INVESTED_AMOUNT_INFLOW_TYPES);
const ACQUIRED_UNITS_INFLOW_TYPES_SQL = toSqlInList(ACQUIRED_UNITS_INFLOW_TYPES);
const COST_BASIS_INVESTED_TYPES_SQL = toSqlInList(COST_BASIS_INVESTED_TYPES);
const DASHBOARD_RETURNS_INVESTED_TYPES_SQL = toSqlInList(DASHBOARD_RETURNS_INVESTED_TYPES);
const COST_BASIS_RECEIVED_TYPES_SQL = toSqlInList(COST_BASIS_RECEIVED_TYPES);
const COST_BASIS_RECEIVED_TYPES_NO_INTEREST_SQL = toSqlInList(COST_BASIS_RECEIVED_TYPES_NO_INTEREST);

module.exports = {
  XIRR_CASH_OUTFLOW_TYPES,
  XIRR_CASH_INFLOW_TYPES,
  INVESTED_AMOUNT_INFLOW_TYPES,
  ACQUIRED_UNITS_INFLOW_TYPES,
  REALIZED_CASHFLOW_TYPES,
  REALIZED_CASHFLOW_TYPES_REINVEST_ACCRUAL,
  INVESTED_AMOUNT_INFLOW_TYPES_SQL,
  ACQUIRED_UNITS_INFLOW_TYPES_SQL,
  COST_BASIS_INVESTED_TYPES,
  DASHBOARD_RETURNS_INVESTED_TYPES,
  COST_BASIS_RECEIVED_TYPES,
  COST_BASIS_RECEIVED_TYPES_NO_INTEREST,
  COST_BASIS_INVESTED_TYPES_SQL,
  DASHBOARD_RETURNS_INVESTED_TYPES_SQL,
  COST_BASIS_RECEIVED_TYPES_SQL,
  COST_BASIS_RECEIVED_TYPES_NO_INTEREST_SQL,
};
